import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { marked } from "marked";

// Be explicit about marked options so the build doesn't silently change rendering
// across versions. Fiche content is generated by Claude (trusted), but disabling
// header ID injection and forcing async=false keeps the surface area small.
marked.setOptions({ breaks: false, gfm: true, headerIds: false, mangle: false, async: false });
import { loadFiche } from "../lib/data.js";
import { useNavigate } from "react-router-dom";
import { speak, loadVoices, NoNorskVoiceError } from "../lib/tts.js";
import { toast } from "../lib/toast.js";

export default function FicheView() {
  const { slug } = useParams();
  const navigate = useNavigate();
  const [md, setMd] = useState(null);
  const [err, setErr] = useState(null);

  useEffect(() => {
    loadFiche(slug).then(setMd).catch(e => setErr(e.message));
    loadVoices();
  }, [slug]);

  useEffect(() => {
    // attach click-to-speak on norsk words inside the rendered content
    const root = document.getElementById("fiche-content");
    if (!root) return;
    const onSpeakErr = (e) => {
      if (e instanceof NoNorskVoiceError) {
        toast("Aucune voix norvégienne installée", {
          type: "warn",
          action: { label: "Réglages", onClick: () => navigate("/settings") },
        });
      }
    };
    const looksLikeNorsk = (s) => /[æøåÅÆØ]|\b(å|er|og|en|et|ei|å)\b/i.test(s);
    const handler = (e) => {
      const sel = window.getSelection?.().toString().trim();
      if (sel && sel.length <= 80) {
        speak(sel).catch(onSpeakErr);
        return;
      }
      // Only react to small leaf elements (table cells, list items) — never paragraphs/headings.
      const target = e.target.closest("td, li");
      if (!target) return;
      // Take only the part before the FR translation marker (—, =, |, :)
      const txt = target.innerText.split(/[—|=:]/)[0].trim();
      if (!txt || txt.length > 60) return;
      // Skip if it doesn't look at all like Norwegian (avoids reading FR with nb voice).
      if (!looksLikeNorsk(txt) && txt.split(/\s+/).length > 4) return;
      speak(txt).catch(onSpeakErr);
    };
    root.addEventListener("click", handler);
    return () => root.removeEventListener("click", handler);
  }, [md]);

  if (err) return <p className="err">Erreur: {err}</p>;
  if (!md) return <p>Chargement…</p>;

  // strip frontmatter from rendered view (keep separately if needed)
  const body = md.startsWith("---") ? md.replace(/^---[\s\S]*?---\n?/, "") : md;

  return (
    <article className="fiche">
      <Link to="/" className="back">← Fiches</Link>
      <div id="fiche-content" dangerouslySetInnerHTML={{ __html: marked.parse(body) }} />
      <p className="hint">💡 Clique un mot ou une ligne pour l'entendre prononcé.</p>
    </article>
  );
}
